[package]
name = "Modern_file_explorer"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.10"
walkdir = "2.3"
chrono = "0.4"
tokio = { version = "1.28", features = ["full"] }
dirs = "5.0"
open = "4.1"
humansize = "2.1"
